"""自动化调试卡点定义（与 docs/AUTOMATION_DEBUG_PLAYBOOK.md 同步）。"""

from typing import Any, Dict, List

AUTOMATION_CHECKPOINTS: List[Dict[str, Any]] = [
    {
        "step": "A0",
        "phase": "Step4 启动预检",
        "order": 0,
        "trigger": "step4 启动 _validate_step4_templates",
        "fail_log": "场景模板缺失",
        "scenes": [],
        "templates": "STEP4 必配 15 场景全部 PNG",
        "ocr": "",
        "debug_where": "agent.log",
        "you_do": "补 templates/ 缺失文件；或 python tools/sync_scene_schemas.py",
        "coord_format": "",
    },
    {
        "step": "A1",
        "phase": "切换入口 / 首帧探测",
        "order": 1,
        "trigger": "switch_to → capture_automation_entry_snapshot",
        "fail_log": "input DataChannel 不可用 / entry 首帧保存失败",
        "scenes": [203, 1, 24, 4, 6],
        "templates": "entry_survey.json 里 matched=true 的场景",
        "ocr": "203: HOME203_NAME/EMAIL（跳过切换用）",
        "debug_where": "logs/manual_capture/{task_id}/ (F9) 或 scene_capture/entry_survey.json",
        "you_do": "F8 人工接管调画面 → F9 截图 → 读 entry_survey 看 matched scene → 报坐标",
        "coord_format": "scene_id + template_id + template四组 + search四组",
    },
    {
        "step": "A7",
        "phase": "主页 OCR 跳过切换（早分支）",
        "order": 2,
        "trigger": "switch_to 入口 _is_already_signed_in_as（在进场景3之前）",
        "fail_log": "主页 OCR 不一致 / debug_home_ocr",
        "scenes": [203],
        "templates": "203.x（磁贴主页）",
        "ocr": "HOME203_NAME_*, HOME203_EMAIL_*",
        "debug_where": "logs/debug_home_ocr_name_*.png, debug_home_ocr_email_*.png",
        "you_do": "203 主页整帧 + 左上角昵称/邮箱两行框坐标",
        "coord_format": "name: L,T,R,B  email: L,T,R,B",
    },
    {
        "step": "A2",
        "phase": "进入档案和系统",
        "order": 3,
        "trigger": "_wait_for_scene(3)",
        "fail_log": "未进入档案和系统页面（场景3）",
        "scenes": [203, 2, 3],
        "templates": "2.1, 2.2, 3.1, 3.2, 3.3",
        "ocr": "",
        "debug_where": "logs/debug_scene3_*.png",
        "you_do": "① 打开 debug_scene3 整帧(缩放到960×540) ② 在「档案和系统」页裁特征 ③ 报 3.x 的 template+search 坐标",
        "coord_format": "template: L,T,R,B  search: L,T,R,B",
    },
    {
        "step": "A3",
        "phase": "添加和切换页",
        "order": 4,
        "trigger": "_wait_for_scene(5)",
        "fail_log": "未进入添加和切换页面（场景5）",
        "scenes": [5],
        "templates": "5.1, 5.2, 5.3",
        "ocr": "",
        "debug_where": "logs/debug_scene5_*.png",
        "you_do": "整帧 + 5.x 模板坐标",
        "coord_format": "template: L,T,R,B  search: L,T,R,B",
    },
    {
        "step": "A4",
        "phase": "选用户（模板）",
        "order": 5,
        "trigger": "_wait_for_scene(6) strict",
        "fail_log": "未进入账号选择页面（场景6）",
        "scenes": [6],
        "templates": "6.1, 6.2",
        "ocr": "",
        "debug_where": "logs/debug_scene6_*.png",
        "you_do": "选用户列表页整帧 + 6.1/6.2 小图坐标",
        "coord_format": "template: L,T,R,B  search: L,T,R,B",
    },
    {
        "step": "A5",
        "phase": "选用户（布局/OCR）",
        "order": 6,
        "trigger": "_verify_scene6_layout / _select_account_by_gamertag",
        "fail_log": "场景6模板误匹配 / 场景6列表 OCR 前布局校验失败 / 无法定位档案",
        "scenes": [6],
        "templates": "(模板已通过则跳过)",
        "ocr": "SCENE6_LIST_*, SCENE6_TEXT_*, SCENE6_ROW_HEIGHT",
        "debug_where": "logs/debug_scene6_*.png",
        "you_do": "标左侧列表大框 + 焦点行文字框（不需裁小模板 PNG）",
        "coord_format": "OCR list: L,T,R,B  text: L,T,R,B  row_height=42",
    },
    {
        "step": "A6",
        "phase": "微软登录页",
        "order": 7,
        "trigger": "_wait_for_scene(10) / 键盘输入",
        "fail_log": "未进入微软登录页（场景10）",
        "scenes": [10],
        "templates": "10.1, 10.2, 10.3 + 键盘 11-64",
        "ocr": "",
        "debug_where": "logs/debug_scene10_*.png",
        "you_do": "登录页整帧 + 10.x；若卡在按键再修 11-64",
        "coord_format": "template: L,T,R,B  search: L,T,R,B",
    },
    {
        "step": "B1",
        "phase": "Xbox 主页启动 FC",
        "order": 8,
        "trigger": "launch_fc_to_ut_menu → scene 203 按 A",
        "fail_log": "仍停留在 Xbox 主页 (scene203) / FC 磁贴焦点未确认",
        "scenes": [203],
        "templates": "203.1, 203.2...",
        "ocr": "",
        "debug_where": "logs/debug_scene203_*.png",
        "you_do": "FC 磁贴获焦/可见状态整帧 + 203.x 坐标",
        "coord_format": "template: L,T,R,B  search: L,T,R,B",
    },
    {
        "step": "B2",
        "phase": "FC 加载 / 登陆游戏",
        "order": 9,
        "trigger": "_wait_for 101, 126",
        "fail_log": "debug_scene101 / debug_scene126",
        "scenes": [101, 126],
        "templates": "101.1, 101.2, 126.1",
        "ocr": "",
        "debug_where": "logs/debug_scene101_*.png, debug_scene126_*.png",
        "you_do": "FC 开场/登陆页整帧 + 模板坐标",
        "coord_format": "template: L,T,R,B  search: L,T,R,B",
    },
    {
        "step": "B3",
        "phase": "UT 主菜单 MAIN_MENU",
        "order": 10,
        "trigger": "_match_expected_screen('MAIN_MENU')",
        "fail_log": "模板匹配超时.*127|147|149",
        "scenes": [127, 147, 149, 101],
        "templates": "127.1, 147.1, 149.1",
        "ocr": "",
        "debug_where": "logs/debug_scene127_*.png, debug_scene147_*.png",
        "you_do": "UT 主菜单整帧 + 127/147/149 坐标",
        "coord_format": "template: L,T,R,B  search: L,T,R,B",
    },
    {
        "step": "C1",
        "phase": "SQB / 比赛导航",
        "order": 11,
        "trigger": "task_type 比赛循环",
        "fail_log": "场景校验超时.*156|166|176",
        "scenes": [156, 166, 176, 189, 191],
        "templates": "156.x, 166.x, 176.x, 189.x",
        "ocr": "",
        "debug_where": "logs/debug_scene*.png",
        "you_do": "卡在哪页截哪页整帧 + 该 scene 全部 template 坐标",
        "coord_format": "template: L,T,R,B  search: L,T,R,B",
    },
]

FAIL_PATTERNS: Dict[str, List[str]] = {
    "A0": [r"场景模板缺失", r"validate_templates"],
    "A1": [r"input DataChannel 不可用", r"entry 首帧保存失败"],
    "A2": [r"未进入档案和系统页面（场景3）", r"debug_scene3_"],
    "A3": [r"未进入添加和切换页面（场景5）", r"debug_scene5_"],
    "A4": [r"未进入账号选择页面（场景6）", r"场景6模板误匹配"],
    "A5": [r"场景6列表 OCR", r"无法定位档案", r"场景6未能 OCR"],
    "A6": [r"未进入微软登录页（场景10）", r"debug_scene10_"],
    "A7": [r"主页 OCR", r"debug_home_ocr"],
    "B1": [r"仍停留在 Xbox 主页 \(scene203\)", r"FC 磁贴", r"debug_scene203_"],
    "B2": [r"debug_scene101_", r"debug_scene126_", r"进 FC 失败"],
    "B3": [r"MAIN_MENU", r"debug_scene127_", r"debug_scene147_"],
    "C1": [r"debug_scene156_", r"debug_scene166_", r"debug_scene176_"],
}
