FROM maven:3.9-eclipse-temurin-17 AS builder

WORKDIR /app

COPY bend-gateway/pom.xml .
COPY bend-gateway/src ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8060

ENTRYPOINT ["java", "-jar", "app.jar"]
