"""xblive 认证错误码（对齐 xblauth Errs）。"""

ERRXS_OK = 0
ERRXS_GET_DEVICE_TOKEN = 10301
ERRXS_SISU_AUTHENTICATE = 10302
ERRXS_OAUTH_AUTHORIZE = 10303
ERRXS_GET_CREDENTIAL_TYPE = 10304
ERRXS_PPSECURE = 10305
ERRXS_OAUTH_TOKEN = 10306
ERRXS_SISU_AUTHORIZE = 10307
ERRXS_XSTS_AUTHORIZE = 10308
ERRXS_XHOME_GET_TOKEN = 10309
ERRXS_QUERY_XHOME_SERVER_EMPTY = 10310
ERRXS_QUERY_XHOME_SERVER_TOO_MUCH = 10311
ERRXS_XHOME_QUERY_CONSOLE = 10312
ERRXS_XAL_WEB = 10405
ERRXS_XAL_MAILBOX = 10406
ERRXS_XAL_PASSWORD = 10407
ERRXS_XAL_PPSECURE_WEB = 10408

_ERROR_NAMES = {
    ERRXS_OK: "OK",
    ERRXS_GET_DEVICE_TOKEN: "GET_DEVICE_TOKEN",
    ERRXS_SISU_AUTHENTICATE: "SISU_AUTHENTICATE",
    ERRXS_OAUTH_AUTHORIZE: "OAUTH_AUTHORIZE",
    ERRXS_GET_CREDENTIAL_TYPE: "GET_CREDENTIAL_TYPE",
    ERRXS_PPSECURE: "PPSECURE",
    ERRXS_OAUTH_TOKEN: "OAUTH_TOKEN",
    ERRXS_SISU_AUTHORIZE: "SISU_AUTHORIZE",
    ERRXS_XSTS_AUTHORIZE: "XSTS_AUTHORIZE",
    ERRXS_XHOME_GET_TOKEN: "XHOME_GET_TOKEN",
    ERRXS_QUERY_XHOME_SERVER_EMPTY: "QUERY_XHOME_SERVER_EMPTY",
    ERRXS_QUERY_XHOME_SERVER_TOO_MUCH: "QUERY_XHOME_SERVER_TOO_MUCH",
    ERRXS_XHOME_QUERY_CONSOLE: "XHOME_QUERY_CONSOLE",
    ERRXS_XAL_WEB: "XAL_WEB",
    ERRXS_XAL_MAILBOX: "XAL_MAILBOX",
    ERRXS_XAL_PASSWORD: "XAL_PASSWORD",
    ERRXS_XAL_PPSECURE_WEB: "XAL_PPSECURE_WEB",
}


def error_code_name(errno: int) -> str:
    return _ERROR_NAMES.get(errno, f"ERRXS_{errno}")
