-- 验证 game_account 表结构
SELECT
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    COLUMN_COMMENT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'bend_platform'
AND TABLE_NAME = 'game_account'
ORDER BY ORDINAL_POSITION;
